
title: "hEGCLC paper"
short_title: "hEGCLC paper"
subtitle: 

Html versions of scripts available in the GitHub repository [EGCLC_paper_release](https://github.com/GiuseppeTestaLab/EGCLC_paper_release).

final: |

pages:

  # =============================
  #         scRNA-Seq analyses
  # =============================
  
   00_ExplorationQC_DimRed_Clustering.ipynb:
      notebook: "scRNASeq/00_Preprocessing/00_ExplorationQC_DimRed_Clustering.ipynb"
      description: First exploration, quality check, dimensionality reduction and clustering of the scRNA-Seq data.

   01a_CellsAnnotationMarkers.ipynb:
      notebook: "scRNASeq/01_Annotation/01a_CellsAnnotationMarkers.ipynb"
      description: Exploration of known markers across clusters of the scRNA-Seq data and cell types annotation.

   01b_FunctionalEnrichment_Clusters.ipynb:
      notebook: "scRNASeq/01_Annotation/01b_FunctionalEnrichment_Clusters.ipynb"
      description: Functional enrichment of the markers of the Leiden clusters.

   01c_CellCycle.ipynb:
      notebook: "scRNASeq/01_Annotation/01c_CellCycle.ipynb"
      description: Analysis of cell cycle phases of the cells in the scRNA-Seq data.

   02a_PseudoBulk_PCA.ipynb:
      notebook: "scRNASeq/02_Pseudobulk/02a_PseudoBulk_PCA.ipynb"
      description: Generation of pseudobulk from annotated scRNA-Seq and PCA analysis.

   02b_Pseudobulk_edgeR_topGO_hEGCLC_hPGCLC.ipynb:
      notebook: "scRNASeq/02_Pseudobulk/02b_Pseudobulk_edgeR_topGO_hEGCLC_hPGCLC.ipynb"
      description: Differential expression analysis and functional enrichment of DEGs from pseudobulks of hPGCLC and hEGCLC.

   02b_Pseudobulk_edgeR_topGO_hiPSC_hEGCLC.ipynb:
      notebook: "scRNASeq/02_Pseudobulk/02b_Pseudobulk_edgeR_topGO_hiPSC_hEGCLC.ipynb"
      description: Differential expression analysis and functional enrichment of DEGs from pseudobulks of hiPSC and hEGCLC.

   02b_Pseudobulk_edgeR_topGO_hiPSC_hPGCLC.ipynb:
      notebook: "scRNASeq/02_Pseudobulk/02b_Pseudobulk_edgeR_topGO_hiPSC_hPGCLC.ipynb"
      description: Differential expression analysis and functional enrichment of DEGs from pseudobulks of hPGCLC and hiPSC.

   02c_Comparisons_between_DEGs.ipynb:
      notebook: "scRNASeq/02_Pseudobulk/02c_Comparisons_between_DEGs.ipynb"
      description: Comparison of DEGs of comparisons hPGCLC-hEGCLC, hiPSC-hEGCLC and hPGCLC-hiPSC.

   03a_Chen_Processing_and_Annotation.ipynb:
      notebook: "scRNASeq/03_Ingestion/03a_Chen_Processing_and_Annotation.ipynb"
      description: Processing of dataset from [Chen et al. (Cell Reports, 2019)](https://doi.org/10.1016/j.celrep.2019.11.083) and annotation of the cell types.

   03b_Ingest_Chen.ipynb:
      notebook: "scRNASeq/03_Ingestion/03b_Ingest_Chen.ipynb"
      description: Ingestion of in-house dataset onto Chen dataset.

   03c_Fetal_Processing_and_Annotation.ipynb:
      notebook: "scRNASeq/03_Ingestion/03c_Fetal_Processing_and_Annotation.ipynb"
      description: Processing of dataset from [Chen et al. (Cell Reports, 2019)](https://doi.org/10.1016/j.celrep.2019.11.083) and annotation of the cell types.

   03d_Ingest_FetalData.ipynb:
      notebook: "scRNASeq/03_Ingestion/03d_Ingest_FetalData.ipynb"
      description: Processing of dataset from [Guo et al. (Cell Reports, 2019)](https://doi.org/10.1016/j.celrep.2019.11.083) and annotation of the cell types.

   04a_DEGs_patterns_AggClustering.ipynb:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/04a_DEGs_patterns_AggClustering.ipynb"
      description: Clustering of genes based on the logFC patterns along the hiPSC-iMeLC-hPGCLC-hEGCLC axis.

   05_TF_activity_inference.ipynb:
      notebook: "scRNASeq/05_TF_analysis/05_TF_activity_inference.ipynb"
      description: Inference of TF activity from scRNA-Seq data using Multivariate Linear Model.

   FuncEnrich_LeidenCluster_0:
      notebook: "scRNASeq/01_Annotation/markers_in_cluster_tables/GO_cluster_0.html"
      description: Functional enrichment of Leiden cluster 0 from clustering in notebook 01

   FuncEnrich_LeidenCluster_1:
      notebook: "scRNASeq/01_Annotation/markers_in_cluster_tables/GO_cluster_1.html"
      description: Functional enrichment of Leiden cluster 1 from clustering in notebook 01

   FuncEnrich_LeidenCluster_2:
      notebook: "scRNASeq/01_Annotation/markers_in_cluster_tables/GO_cluster_2.html"
      description: Functional enrichment of Leiden cluster 2 from clustering in notebook 01

   FuncEnrich_LeidenCluster_3:
      notebook: "scRNASeq/01_Annotation/markers_in_cluster_tables/GO_cluster_3.html"
      description: Functional enrichment of Leiden cluster 3 from clustering in notebook 01

   FuncEnrich_LeidenCluster_4:
      notebook: "scRNASeq/01_Annotation/markers_in_cluster_tables/GO_cluster_4.html"
      description: Functional enrichment of Leiden cluster 4 from clustering in notebook 01

   FuncEnrich_LeidenCluster_5:
      notebook: "scRNASeq/01_Annotation/markers_in_cluster_tables/GO_cluster_5.html"
      description: Functional enrichment of Leiden cluster 5 from clustering in notebook 01

   FuncEnrich_LeidenCluster_6:
      notebook: "scRNASeq/01_Annotation/markers_in_cluster_tables/GO_cluster_6.html"
      description: Functional enrichment of Leiden cluster 6 from clustering in notebook 01

   FuncEnrich_LeidenCluster_7:
      notebook: "scRNASeq/01_Annotation/markers_in_cluster_tables/GO_cluster_7.html"
      description: Functional enrichment of Leiden cluster 7 from clustering in notebook 01

   FuncEnrich_LeidenCluster_8:
      notebook: "scRNASeq/01_Annotation/markers_in_cluster_tables/GO_cluster_8.html"
      description: Functional enrichment of Leiden cluster 8 from clustering in notebook 01

   FuncEnrich_LeidenCluster_9:
      notebook: "scRNASeq/01_Annotation/markers_in_cluster_tables/GO_cluster_9.html"
      description: Functional enrichment of Leiden cluster 9 from clustering in notebook 01

   FuncEnrich_LeidenCluster_10:
      notebook: "scRNASeq/01_Annotation/markers_in_cluster_tables/GO_cluster_10.html"
      description: Functional enrichment of Leiden cluster 10 from clustering in notebook 01

   FuncEnrich_LeidenCluster_11:
      notebook: "scRNASeq/01_Annotation/markers_in_cluster_tables/GO_cluster_11.html"
      description: Functional enrichment of Leiden cluster 11 from clustering in notebook 01

   FuncEnrich_LeidenCluster_12:
      notebook: "scRNASeq/01_Annotation/markers_in_cluster_tables/GO_cluster_12.html"
      description: Functional enrichment of Leiden cluster 12 from clustering in notebook 01

   FuncEnrich_GenesCluster_0:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_0.html"
      description: Functional enrichment of genes in cluster 0 from clustering in notebook 04a

   FuncEnrich_GenesCluster_1:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_1.html"
      description: Functional enrichment of genes in cluster 1 from clustering in notebook 04a

   FuncEnrich_GenesCluster_2:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_2.html"
      description: Functional enrichment of genes in cluster 2 from clustering in notebook 04a

   FuncEnrich_GenesCluster_3:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_3.html"
      description: Functional enrichment of genes in cluster 3 from clustering in notebook 04a

   FuncEnrich_GenesCluster_4:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_4.html"
      description: Functional enrichment of genes in cluster 4 from clustering in notebook 04a

   FuncEnrich_GenesCluster_5:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_5.html"
      description: Functional enrichment of genes in cluster 5 from clustering in notebook 04a

   FuncEnrich_GenesCluster_6:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_6.html"
      description: Functional enrichment of genes in cluster 6 from clustering in notebook 04a

   FuncEnrich_GenesCluster_7:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_7.html"
      description: Functional enrichment of genes in cluster 7 from clustering in notebook 04a

   FuncEnrich_GenesCluster_8:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_8.html"
      description: Functional enrichment of genes in cluster 8 from clustering in notebook 04a

   FuncEnrich_GenesCluster_9:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_9.html"
      description: Functional enrichment of genes in cluster 9 from clustering in notebook 04a

   FuncEnrich_GenesCluster_10:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_10.html"
      description: Functional enrichment of genes in cluster 10 from clustering in notebook 04a

   FuncEnrich_GenesCluster_11:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_11.html"
      description: Functional enrichment of genes in cluster 11 from clustering in notebook 04a

   FuncEnrich_GenesCluster_12:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_12.html"
      description: Functional enrichment of genes in cluster 12 from clustering in notebook 04a

   FuncEnrich_GenesCluster_13:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_13.html"
      description: Functional enrichment of genes in cluster 13 from clustering in notebook 04a

   FuncEnrich_GenesCluster_14:
      notebook: "scRNASeq/04_edgeR_DEGs_inTime/html/GO_cluster_14.html"
      description: Functional enrichment of genes in cluster 14 from clustering in notebook 04a

  # =============================
  #         GRN analyses
  # =============================

   06.1_CellOracle.ipynb:
      notebook: "scRNASeq/06_GRNs/1_CellOracle.ipynb"
      description: |

   06.2_CellOracle.ipynb:
      notebook: "scRNASeq/06_GRNs/2_CellOracle.ipynb"
      description: |

   06.3_CellOracle.ipynb:
      notebook: "scRNASeq/06_GRNs/3_CellOracle.ipynb"
      description: |

   06_GRN_DMDE.ipynb:
      notebook: "scRNASeq/06_GRNs/GRN_DMDE.ipynb"
      description: |

   06_GRN_hEGCLC.ipynb:
      notebook: "scRNASeq/06_GRNs/GRN_hEGCLC.ipynb"
      description: |

   06_GRN_hPGCLC.ipynb:
      notebook: "scRNASeq/06_GRNs/GRN_hPGCLC.ipynb"
      description: |

   06_GRN_hiPSC.ipynb:
      notebook: "scRNASeq/06_GRNs/GRN_hiPSC.ipynb"
      description: |

   06_GRN_iMeLC.ipynb:
      notebook: "scRNASeq/06_GRNs/GRN_iMeLC.ipynb"
      description: |

  # =============================
  #         EMSeq analyses
  # =============================

  # -----------------------------
  # 1. Core EMSeq Analysis
  # -----------------------------
  
  PreliminaryExploration:
    notebook: "EMSeq/1.ExploratoryAnalysis/PreliminaryExploration.html"
    description: Preliminary exploration of DNA methylation profiles.

  DMRCalling:
    notebook: "EMSeq/2.DifferentialAnalysis/DMRCalling.html"
    description: Differentially methylated regions (DMRs) identification.

  TwistBedAnnotation:
    notebook: "EMSeq/3.TwistRegionAnnotation/TwistBedAnnotation.html"
    description: Functional and genomic annotation of targeted Twist regions.

  DMRAnnotation:
    notebook: "EMSeq/4.DMRAnnotation/DMRAnnotation.html"
    description: Functional and genomic annotation of identified DMRs.

  DMRplots:
    notebook: "EMSeq/5.DMRInterpretation/DMRVisualization/DMRplots.html"
    description: Visualization of DMR methylation patterns across samples.

  TopGO_hiPSCs_vs_hPGCLCs_all:
    notebook: "EMSeq/5.DMRInterpretation/TopGO/TopGO_hiPSCs_vs_hPGCLCs_all.html"
    description: GO enrichment analysis for DMR-associated genes in hiPSCs vs hPGCLCs.

  TopGO_iMeLCs_vs_hPGCLCs_all:
    notebook: "EMSeq/5.DMRInterpretation/TopGO/TopGO_iMeLCs_vs_hPGCLCs_all.html"
    description: GO enrichment analysis for DMR-associated genes in iMeLCs vs hPGCLCs.

  TopGO_hEGCLCs_vs_hiPSCs_all:
    notebook: "EMSeq/5.DMRInterpretation/TopGO/TopGO_hEGCLCs_vs_hiPSCs_all.html"
    description: GO enrichment analysis for DMR-associated genes in hEGCLCs vs hiPSCs.

  TopGO_hEGCLCs_vs_hPGCLCs_all:
    notebook: "EMSeq/5.DMRInterpretation/TopGO/TopGO_hEGCLCs_vs_hPGCLCs_all.html"
    description: GO enrichment analysis for DMR-associated genes in hEGCLCs vs hPGCLCs.

  Heatmaps_imprinted_regions:
    notebook: "EMSeq/6.ImprintedExploration/Heatmaps_imprinted_regions.html"
    description: Heatmap visualization of methylation in imprinted regions.

  DMRplots_imprinted_regions:
    notebook: "EMSeq/6.ImprintedExploration/DMRplots_imprinted_regions.html"
    description: Visualization of methylation patterns in imprinted genomic regions.

  # -----------------------------
  # 2. Tang Dataset (Escapees)
  # -----------------------------
  
  1.EscapeeBsseqGeneration_Tang:
    notebook: "EMSeq/7.EscapeesExploration/1.EscapeeBsseqGeneration_Tang.html"
    description: Generation of bsseq object with measured CpGs within Tang escapee regions.

  2.EscapeeAnnotationAndFunctional_Tang:
    notebook: "EMSeq/7.EscapeesExploration/2.EscapeeAnnotationAndFunctional_Tang.html"
    description: Functional annotation Tang escapee regions and GO of associated genes.

  3.EscapeeHeatmaps_Tang:
    notebook: "EMSeq/7.EscapeesExploration/3.EscapeeHeatmaps_Tang.html"
    description: Heatmap visualization of Tang escapee methylation profiles across samples.

  4.EscapeesvsNonEscapees_Tang:
    notebook: "EMSeq/7.EscapeesExploration/4.EscapeesvsNonEscapees_Tang.html"
    description: Comparative analysis between Tang escapee and non-escapee regions methylation profiles.

  # -----------------------------
  # 3. Mitinori Dataset (Escapees)
  # -----------------------------
  
  1.EscapeeBsseqGeneration_Mitinori:
    notebook: "EMSeq/7.EscapeesExploration/MitinoriEscapees/1.EscapeeBsseqGeneration_Mitinori.html"
    description: Generation of bsseq object with measured CpGs within Mitinori escapee regions.

  2.EscapeeAnnotationAndFunctional_Mitinori:
    notebook: "EMSeq/7.EscapeesExploration/MitinoriEscapees/2.EscapeeAnnotationAndFunctional_Mitinori.html"
    description: Functional annotation Mitinori escapee regions and GO of associated genes.

  3.EscapeeHeatmaps_Mitinori:
    notebook: "EMSeq/7.EscapeesExploration/MitinoriEscapees/3.EscapeeHeatmaps_Mitinori.html"
    description: Heatmap visualization of Mitinori escapee methylation profiles across samples.

  4.EscapeesvsNonEscapees_Mitinori:
    notebook: "EMSeq/7.EscapeesExploration/MitinoriEscapees/4.EscapeesvsNonEscapees_Mitinori.html"
    description: Comparative analysis between Mitinori escapee and non-escapee regions methylation profiles.

  # -----------------------------
  # 4. Hsu Dataset (Exploration)
  # -----------------------------
  
  1.HsuExploration_WGBS:
    notebook: "EMSeq/8.HsuExploration/1.HsuExploration_WGBS.html"
    description: Exploration of Whole-genome bisulfite sequencing (WGBS) data from Hsu datasets.

  2.HsuExploration_bACEseq:
    notebook: "EMSeq/8.HsuExploration/2.HsuExploration_bACEseq.html"
    description: Exploration of bACE-seq data from Hsu datasets.

  3.HsuExploration_WGBSandbACEseq:
    notebook: "EMSeq/8.HsuExploration/3.HsuExploration_WGBSandbACEseq.html"
    description: Generation of bsseq object with WGBS and bACE-seq data from Hsu datasets.

  # -----------------------------
  # 5. Hsu–Tang Joint Escapees
  # -----------------------------
  
  1.EscapeeBsseqGeneration_Hsu_Tang:
    notebook: "EMSeq/8.HsuExploration/Escapees_Hsu_Tang/1.EscapeeBsseqGeneration_Hsu_Tang.html"
    description: Generation of bsseq object with Hsu CpGs within Tang escapee regions.

  2.EscapeeAnnotationAndFunctional_Hsu_Tang:
    notebook: "EMSeq/8.HsuExploration/Escapees_Hsu_Tang/2.EscapeeAnnotationAndFunctional_Hsu_Tang.html"
    description: Functional annotation Tang escapee regions in Hsu dataset and GO of associated genes.

  3.EscapeeHeatmaps_Hsu_Tang:
    notebook: "EMSeq/8.HsuExploration/Escapees_Hsu_Tang/3.EscapeeHeatmaps_Hsu_Tang.html"
    description: Heatmap visualization of methylation patterns in Hsu–Tang escapee regions.

  4.EscapeesvsNonEscapees_Hsu_Tang:
    notebook: "EMSeq/8.HsuExploration/Escapees_Hsu_Tang/4.EscapeesvsNonEscapees_Hsu_Tang.html"
    description: Comparative analysis between escapee and non-escapee regions in combined Hsu–Tang dataset.

  # -----------------------------
  # 6. EGCLC Passage 10 (p10)
  # -----------------------------
  
  EGCLC_p10_PreliminaryExploration:
    notebook: "EMSeq/9.EGCLC_p10/1.ExploratoryAnalysis/0.PreliminaryExploration.html"
    description: Preliminary methylation data exploration adding EGCLC passage 10 samples.

  EGCLC_p10_DMRCalling:
    notebook: "EMSeq/9.EGCLC_p10/2.DifferentialAnalysis/DMRCalling.html"
    description: Differentially methylated regions (DMRs) identification adding EGCLC passage 10 samples.

  EGCLC_p10_DMRAnnotation:
    notebook: "EMSeq/9.EGCLC_p10/3.DMRAnnotation/DMRAnnotation.html"
    description: Functional and genomic annotation of identified DMRs adding EGCLC passage 10 samples.

  EGCLC_p10_DMRplots:
    notebook: "EMSeq/9.EGCLC_p10/4.DMRInterpretation/DMRplots.html"
    description: Visualization of DMR methylation patterns across samples including EGCLC passage 10 ones.

  EGCLC_p10_Heatmaps_imprinted_regions:
    notebook: "EMSeq/9.EGCLC_p10/5.ImprintedExploration/Heatmaps_imprinted_regions.html"
    description: Heatmap visualization of methylation in imprinted regions adding EGCLC passage 10 samples.

  EGCLC_p10_DMRplots_imprinted_regions:
    notebook: "EMSeq/9.EGCLC_p10/5.ImprintedExploration/DMRplots_imprinted_regions.html"
    description: Visualization of methylation patterns in imprinted genomic regions adding EGCLC passage 10 samples.

  EGCLC_p10_1.EscapeeBsseqGeneration:
    notebook: "EMSeq/9.EGCLC_p10/6.EscapeesExploration/1.EscapeeBsseqGeneration.html"
    description: Generation of bsseq object with measured CpGs within Tang escapee regions including EGCLC passage 10 samples.

  EGCLC_p10_2.EscapeeAnnotationAndFunctional:
    notebook: "EMSeq/9.EGCLC_p10/6.EscapeesExploration/2.EscapeeAnnotationAndFunctional.html"
    description: Functional annotation Tang escapee regions and GO of associated genes (from bsseq object including EGCLC passage 10 samples).

  EGCLC_p10_3.EscapeeHeatmaps:
    notebook: "EMSeq/9.EGCLC_p10/6.EscapeesExploration/3.EscapeeHeatmaps.html"
    description: Heatmap visualization of Mitinori escapee methylation profiles across samples including EGCLC passage 10 ones.

  EGCLC_p10_4.EscapeesvsNonEscapees:
    notebook: "EMSeq/9.EGCLC_p10/6.EscapeesExploration/4.EscapeesvsNonEscapees.html"
    description: Comparative analysis between Tang escapee and non-escapee regions methylation profiles across samples including EGCLC passage 10 ones.
